ALTER USER
CREATE DATABASE IF NOT EXISTS wordpress DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER IF NOT EXISTS '$MARIADB_USER'@'localhost' IDENTIFIED BY '$MARIADB_PASSWD';
GRANT ALL PRIVILEGES ON wordpress.* TO '$MARIADB_USER'@'localhost';
FLUSH PRIVILEGES;
