services:
  ftp:
    build: ./sources/ftp
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 4000-4100:4000-4100
    volumes:
      - /srv/ftp:/srv/ftp
    secrets:
      - ftps-cert
      - ftps-key

secrets:
  ftps-cert:
    file: ./sources/ftp/.secret/vsftpd.crt
  ftps-key:
    file: ./sources/ftp/.secret/vsftpd.key
  https-certificate:
    file: ./sources/nginx/.secret

networks:
  isolated:
    driver: bridge
