events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate /run/secrets/nginx.crt;
        ssl_certificate_key /run/secrets/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        index index.php index.html;
        access_log  /var/log/nginx/nginx_access.log;
        error_log /var/log/nginx/nginx_error.log;
        root /srv/www/wordpress;

        location = /static {
            return 301 /static/;
        }

        location /static/ {
            root /srv/www/wordpress;
            try_files $uri $uri/ =404;
        }
        location = /adminer {
            include fastcgi_params;

            fastcgi_param SCRIPT_FILENAME /var/www/adminer/index.php;
            fastcgi_param SCRIPT_NAME /adminer;

            fastcgi_pass adminer:4444;
        }

        location = /adminer/ {
            include fastcgi_params;

            fastcgi_param SCRIPT_FILENAME /var/www/adminer/index.php;
            fastcgi_param SCRIPT_NAME /adminer/;

            fastcgi_pass adminer:4444;
        }

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            try_files $uri =404;

            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location ~ /\. {
            deny all;
        }
    }

    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }
}
