server {
	server_name invalid;
	listen		80 default;
	return		404;
}

server
{
	listen					443 ssl;
	server_name				revers-proxy;
	ssl_certificate			/etc/nginx/ssl/nginx.crt;
	ssl_certificate_key 	/etc/nginx/ssl/nginx.key;
	return					404;
}
