events {
	worker_connections 1024;
}

http {
	server {
		listen 443 ssl;

		server_name https_reverse_proxy;

		ssl_certificate /run/secrets/nginx.crt;
		ssl_certificate_key /run/secrets/nginx.key;
		ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;

		location / {
			root /var/www/data;
		}
	}
	server {
		listen 80;

		server_name http_redirect;
		return 301 https://api.myip.com;
	}
}
