
# --- BASIS PARAMETER ---
listen=YES
listen_ipv6=NO
anonymous_enable=NO # Accept anonymous/anonymous user
local_enable=YES
write_enable=YES
local_umask=022 # ???
ftpd_banner="Welcome to Gun8hoot Inception ftp server" # Text who is display when a user is connected


local_root=/srv/ftp
allow_writeable_chroot=YES
#chroot_local_user=NO
#chroot_list_enable=YES

# --- PASSIV MODE ---
pasv_enable=YES
pasv_min_port=4000
pasv_max_port=4100

# --- TLS ---
ssl_enable=YES
force_local_logins_ssl=YES
force_local_data_ssl=YES
ssl_tlsv1=YES # For TLS 1.3 ???
rsa_cert_file=/var/ftp/cert/vsftpd.crt
rsa_private_key_file=/var/ftp/cert/vsftpd.key
