FROM alpine:3.22
WORKDIR /tmp
RUN apk update && \
	apk add lighttpd php fcgi php-cgi unzip

COPY ./latest.zip /tmp/latest.zip
COPY ./install.sh /tmp/entrypoint.sh

# TEST WITHOUT NGINX
EXPOSE 80
ENTRYPOINT [ "sh", "/tmp/entrypoint.sh" ]
