services:
    # -- MENDATORY PART --
    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        secrets:
            - nginx.crt
            - nginx.key
        restart: on-failure:5
        networks:
            - MainNet
        volumes:
            - wordpress_data:/srv/www/wordpress
            - static_pages:/srv/www/wordpress/static
            - adminer_page:/var/www/adminer/
            - logs:/var/log/nginx
        depends_on:
            - wordpress
            - adminer
            - gitea
    mariadb:
        container_name: database
        build:
            context: ./database
            dockerfile: Dockerfile
        networks:
            - MainNet
        restart: on-failure:5
        volumes:
            - db:/var/lib/mysql
            - logs:/var/logs/mariadb
        environment:
            - MARIADB_USER=${MARIADB_USERNAME}
            - MARIADB_PASSWD=${MARIADB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    wordpress:
        container_name: wordpress
        build:
            context: ./wordpress
            dockerfile: Dockerfile
        networks:
            - MainNet
        environment:
            - MARIADB_USER=${MARIADB_USERNAME}
            - MARIADB_PASSWD=${MARIADB_PASSWORD}
        restart: on-failure:5
        volumes:
            - wordpress_data:/srv/www/wordpress
        depends_on:
            - mariadb

    # -- BONUS PART --
    ftp:
        container_name: ftp
        build:
            context: ./ftp
            dockerfile: Dockerfile
        ports:
            - "21:21"
            - "40000-40100:40000-40100"
        volumes:
            - $HOME/data/ftp:/srv/ftp
        environment:
            - FTP_PASSWORD=${FTP_PASSWORD}
        secrets:
            - vsftpd.crt
            - vsftpd.key
        restart: on-failure:5
        networks:
            - MainNet
        depends_on:
            - nginx
    adminer:
        container_name: adminer
        build:
            context: ./adminer
            dockerfile: Dockerfile
        volumes:
            - adminer_page:/var/www/adminer/
        restart: on-failure:5
        networks:
            - MainNet
        depends_on:
            - mariadb
    redis:
        container_name: redis
        build:
            context: ./redis
            dockerfile: Dockerfile
        networks:
            - MainNet
        restart: on-failure:5
        depends_on:
            - wordpress
    kuma:
        container_name: kuma
        build:
            context: ./kuma
            dockerfile: Dockerfile
        networks:
            - MainNet
        ports:
            - 3001:3001
        restart: on-failure:5
        depends_on:
            - wordpress
    kuma-mariadb:
        container_name: kumadb
        build:
            context: ./kuma/db
            dockerfile: Dockerfile
        networks:
            - MainNet
        restart: on-failure:5
        volumes:
            - kuma_data:/var/lib/mysql
            - logs:/var/logs/mariadb
        environment:
            - KUMA_USER=${KUMA_USERNAME}
            - KUMA_PASSWD=${KUMA_PASSWORD}
            - KUMA_ROOT_PASSWORD=${KUMA_ROOT_PASSWORD}
    #     -- GITEA --
    gitea:
        container_name: gitea
        build:
            context: ./gitea
            dockerfile: Dockerfile
        networks:
            - MainNet
        ports:
            - 3000:3000
        restart: on-failure:5
        depends_on:
            - mariadb
    postgres_gitea:
        container_name: postgres_gitea
        build:
            context: ./gitea/postgres
            dockerfile: Dockerfile
        networks:
            - MainNet
        restart: on-failure:5
        volumes:
            - postgres_gitea:/srv/postgres
        depends_on:
            - gitea


secrets:
    # -- FTP TLS CERTIFICATE --
    vsftpd.crt:
        file: ./.cert/vsftpd.crt
    vsftpd.key:
        file: ./.cert/vsftpd.key
    # -- HTTPS TLS CERTIFICATE --
    nginx.key:
        file: ./.cert/nginx.key
    nginx.crt:
        file: ./.cert/nginx.crt

volumes:
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/mariadb
    wordpress_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/wordpress
    adminer_page:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $PWD/adminer/frontend
    static_pages:
        driver: local
        driver_opts:
            type: none
            o: bind, ro
            device: $PWD/nginx/static
    logs:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/logs
    postgres_gitea:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/postgres_gitea
    kuma_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/kuma_db

networks:
    MainNet:
        driver: bridge
    KumaNetwork: {}
    WPNetwork:
        driver: bridge
