services:
    # -- MENDATORY PART --
    nginx:
        container_name: inception-nginx
        build:
            context: ./src/nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        secrets:
            - nginx.crt
            - nginx.key
        restart: on-failure:5
        networks:
            - MainNet
        volumes:
            - wordpress_data:/srv/www/wordpress
            - static_pages:/srv/www/wordpress/static
            - adminer_page:/var/www/adminer/
            - logs:/var/log/nginx
        depends_on:
            - wordpress
            - adminer
    mariadb:
        container_name: inception-mariadb
        build:
            context: ./src/mariadb
            dockerfile: Dockerfile
        networks:
            - DBNetwork
        restart: on-failure:5
        volumes:
            - db:/var/lib/mysql
            - logs:/var/logs/mariadb
        environment:
            - MARIADB_USER=${MARIADB_USERNAME}
            - MARIADB_PASSWD=${MARIADB_PASSWORD}
            - KUMA_DB_USER=${KUMA_DB_USER}
            - KUMA_DB_PASSWD=${KUMA_DB_PASSWD}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    wordpress:
        container_name: inception-wordpress
        build:
            context: ./src/wordpress
            dockerfile: Dockerfile
        networks:
            - MainNet
            - DBNetwork
            - RedisNetwork
        environment:
            - MARIADB_USER=${MARIADB_USERNAME}
            - MARIADB_PASSWD=${MARIADB_PASSWORD}
        restart: on-failure:5
        volumes:
            - wordpress_data:/srv/www/wordpress
        depends_on:
            - mariadb

    # -- BONUS PART --
    ftp:
        container_name: inception-ftp
        build:
            context: ./src/ftp
            dockerfile: Dockerfile
        ports:
            - "21:21"
            - "40000-40100:40000-40100"
        volumes:
            - $HOME/data/ftp:/srv/ftp
        environment:
            - FTP_PASSWORD=${FTP_PASSWORD}
        secrets:
            - vsftpd.crt
            - vsftpd.key
        restart: on-failure:5
        networks:
            - MainNet
    adminer:
        container_name: inception-adminer
        build:
            context: ./src/adminer
            dockerfile: Dockerfile
        volumes:
            - adminer_page:/var/www/adminer/
        restart: on-failure:5
        networks:
            - MainNet
            - DBNetwork
        depends_on:
            - mariadb
    redis:
        container_name: inception-redis
        build:
            context: ./src/redis
            dockerfile: Dockerfile
        networks:
            - RedisNetwork
        restart: on-failure:5
        depends_on:
            - wordpress
    kuma:
        container_name: inception-kuma
        build:
            context: ./src/kuma
            dockerfile: Dockerfile
        networks:
            - MainNet
            - DBNetwork
        restart: on-failure:5
        depends_on:
            - wordpress

secrets:
    # -- FTP TLS CERTIFICATE --
    vsftpd.crt:
        file: ./.cert/vsftpd.crt
    vsftpd.key:
        file: ./.cert/vsftpd.key
    # -- HTTPS TLS CERTIFICATE --
    nginx.key:
        file: ./.cert/nginx.key
    nginx.crt:
        file: ./.cert/nginx.crt

volumes:
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/mariadb
    wordpress_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/wordpress
    adminer_page:
        driver: local
        driver_opts:
            type: none
            o: bind, ro
            device: $HOME/data/adminer
    static_pages:
        driver: local
        driver_opts:
            type: none
            o: bind, ro
            device: $PWD/src/nginx/static
    logs:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/logs
    kuma_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: $HOME/data/kuma_db

networks:
    MainNet:
        driver: bridge
    DBNetwork: {internal: true}
    RedisNetwork: {internal: true}
    WPNetwork: {internal: true}
